# Generated by Django 5.2.16 on 2026-08-07 07:25

import uuid

from django.db import migrations, models

import apps.common.fields
import apps.common.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("short_name", models.CharField(max_length=20, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                (
                    "logo",
                    apps.common.fields.CloudinaryImageField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
                "ordering": ["name"],
            },
            bases=(apps.common.mixins.AutoSlugMixin, models.Model),
        ),
    ]
