# Generated by Django 5.2.16 on 2026-08-08 16:40

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["parent", "display_order"],
                        name="category_parent_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_deleted", False), ("parent__isnull", True)
                        ),
                        fields=("name",),
                        name="unique_alive_root_category_name",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_deleted", False), ("parent__isnull", False)
                        ),
                        fields=("parent", "name"),
                        name="unique_alive_child_category_name_per_parent",
                    ),
                ],
            },
            bases=(apps.common.mixins.AutoSlugMixin, models.Model),
        ),
    ]
