# Generated by Django 5.2.16 on 2026-08-08 00:11

from django.db import migrations, models

import apps.common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[apps.common.validators.validate_phone_number],
            ),
        ),
    ]
