# Generated by Django 5.2.16 on 2026-08-08 08:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.fields
import apps.common.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("universities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student Vendor"),
                            ("BUSINESS", "Business Vendor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("store_name", models.CharField(max_length=150)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[apps.common.validators.validate_phone_number],
                    ),
                ),
                (
                    "matric_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("level", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "business_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_logo",
                    apps.common.fields.CloudinaryImageField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_profiles",
                        to="universities.university",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ADMISSION_LETTER", "Admission Letter"),
                            ("STUDENT_ID_CARD", "Student ID Card"),
                            ("COURSE_REGISTRATION_SLIP", "Course Registration Slip"),
                            ("SCHOOL_FEE_RECEIPT", "School Fee Receipt"),
                            ("BUSINESS_DOCUMENT", "Business Document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", apps.common.fields.CloudinaryDocumentField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vendors.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="vendorprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("matric_number__isnull", False)),
                fields=("university", "matric_number"),
                name="unique_matric_number_per_university",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("department__isnull", False),
                        ("level__isnull", False),
                        ("matric_number__isnull", False),
                        ("vendor_type", "STUDENT"),
                    ),
                    models.Q(
                        ("business_address__isnull", False),
                        ("business_name__isnull", False),
                        ("vendor_type", "BUSINESS"),
                    ),
                    _connector="OR",
                ),
                name="vendor_type_required_fields",
            ),
        ),
    ]
