# Generated by Django 5.2.16 on 2026-08-08 10:06

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.mixins
import apps.common.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("display_name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=170, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[apps.common.validators.validate_phone_number],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "vendor_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store",
                        to="vendors.vendorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(apps.common.mixins.AutoSlugMixin, models.Model),
        ),
    ]
